// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"meowchat-system/biz/adaptor"
	"meowchat-system/biz/application/service"
	"meowchat-system/biz/infrastructure/config"
	"meowchat-system/biz/infrastructure/mapper"
)

// Injectors from wire.go:

func NewSystemServerImpl() (*adaptor.SystemServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	adminModel := mapper.NewAdminModel(configConfig)
	applyModel := mapper.NewApplyModel(configConfig)
	communityModel := mapper.NewCommunityModel(configConfig)
	newsModel := mapper.NewNewsModel(configConfig)
	noticeModel := mapper.NewNoticeModel(configConfig)
	userRoleModel := mapper.NewUserRoleModel(configConfig)
	systemServiceImpl := &service.SystemServiceImpl{
		AdminModel:     adminModel,
		ApplyModel:     applyModel,
		CommunityModel: communityModel,
		NewsModel:      newsModel,
		NoticeModel:    noticeModel,
		UserRoleModel:  userRoleModel,
	}
	systemServerImpl := &adaptor.SystemServerImpl{
		Config:        configConfig,
		SystemService: systemServiceImpl,
	}
	return systemServerImpl, nil
}
