// Code generated by goctl. DO NOT EDIT.
package notice

import (
	"context"
	"github.com/xh-polaris/meowchat-system/biz/infrastructure/data/db"
	"github.com/xh-polaris/meowchat-system/biz/infrastructure/mapper"

	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixNoticeCacheKey = "cache:notice:"

type noticeModel interface {
	Insert(ctx context.Context, data *db.Notice) error
	FindOne(ctx context.Context, id string) (*db.Notice, error)
	Update(ctx context.Context, data *db.Notice) error
	Delete(ctx context.Context, id string) error
}

type defaultNoticeModel struct {
	conn *monc.Model
}

func newDefaultNoticeModel(conn *monc.Model) *defaultNoticeModel {
	return &defaultNoticeModel{conn: conn}
}

func (m *defaultNoticeModel) Insert(ctx context.Context, data *db.Notice) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixNoticeCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultNoticeModel) FindOne(ctx context.Context, id string) (*db.Notice, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, mapper.ErrInvalidObjectId
	}

	var data db.Notice
	key := prefixNoticeCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, mapper.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeModel) Update(ctx context.Context, data *db.Notice) error {
	data.UpdateAt = time.Now()
	key := prefixNoticeCacheKey + data.ID.Hex()
	_, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultNoticeModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return mapper.ErrInvalidObjectId
	}
	key := prefixNoticeCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
